enum AppErrors {
  USER_CREATED = 'USER_CREATED',
  VERIF_STARTED = 'VERIF_STARTED',
  VERIF_COMPLETED = 'VERIF_COMPLETED',
  VERIF_NOT_FOUND = 'VERIF_NOT_FOUND',
  VERIF_CHANGE_FORBIDDEN = 'VERIF_CHANGE_FORBIDDEN',
}

export default AppErrors;
